In [ ]:
#NUMPY
import numpy as np

# 1. Create a 1D NumPy Array
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("Week 1 Temperatures:")
print(temperatures_w1)



Week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [2]:
# 2. Inspection and Properties
print("\nShape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)



Shape: (7,)
Data Type: float64
Number of Elements: 7


In [3]:
# 3. Convert Celsius to Fahrenheit
temperatures_f = (temperatures_w1 * 9/5) + 32

print("\nTemperatures in Fahrenheit:")
print(temperatures_f)

# Maximum, Minimum and Mean
print("\nMaximum Temperature:", np.max(temperatures_w1))
print("Minimum Temperature:", np.min(temperatures_w1))
print("Mean Temperature:", round(np.mean(temperatures_w1), 2))



Temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.54


In [4]:
# 4. Array Slicing and Indexing
first_three_days = temperatures_w1[:3]
weekend = temperatures_w1[-2:]
middle_three_days = temperatures_w1[2:5]

print("\nFirst Three Days:", first_three_days)
print("Weekend:", weekend)
print("Middle Three Days:", middle_three_days)


First Three Days: [22.5 25.3 20.8]
Weekend: [24.8 21.9]
Middle Three Days: [20.8 23.4 26.1]


In [5]:
# 5. Create a 2D Array
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print("\n2D Temperature Array:")
print(temperatures)


2D Temperature Array:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [6]:
# 6. Inspect the 2D Array
print("\n2D Array Shape:", temperatures.shape)
print("2D Array Data Type:", temperatures.dtype)
print("Total Number of Elements:", temperatures.size)



2D Array Shape: (2, 7)
2D Array Data Type: float64
Total Number of Elements: 14


In [7]:
# Extract each week
week1 = temperatures[0]
week2 = temperatures[1]

print("\nWeek 1:", week1)
print("Week 2:", week2)


Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [8]:

# Extract weekends for both weeks
weekends = temperatures[:, -2:]

print("\nWeekend Temperatures for Both Weeks:")
print(weekends)


Weekend Temperatures for Both Weeks:
[[24.8 21.9]
 [22.8 20.1]]


In [9]:
#PANDAS
import pandas as pd

# 1. Creating Pandas Series
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print("Marks Series:")
print(marks)

Marks Series:
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [10]:
# 2. Indexing and Slicing

# Mark of 1st rank student
print("\nMark of 1st rank student:")
print(marks.iloc[0])

# Top 3 ranks using loc
print("\nTop 3 ranks:")
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

# Mark of 3rd rank student using iloc
print("\nMark of 3rd rank student:")
print(marks.iloc[2])

# Marks greater than 90
print("\nRanks with marks greater than 90:")
print(marks[marks > 90])


Mark of 1st rank student:
95

Top 3 ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64

Mark of 3rd rank student:
89

Ranks with marks greater than 90:
Rank1    95
Rank2    92
dtype: int64


In [11]:
# 3. Manipulating Series

# Modify Rank1 mark
marks.loc['Rank1'] = 100

print("\nAfter modifying Rank1:")
print(marks)

# Remove Rank5
marks = marks.drop('Rank5')

print("\nAfter removing Rank5:")
print(marks)

# Calculate CGPA
cgpa = marks / 10

print("\nCGPA:")
print(cgpa)


After modifying Rank1:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

After removing Rank5:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [12]:
#PANDAS DATAFRAME

# 1. Creating Pandas DataFrame

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],

    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],

    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})


In [17]:
# 2. Data Exploration

# Display DataFrame
print("Transactions DataFrame:")
print(transactions)

# Head
print("\nFirst 5 rows:")
print(transactions.head())

# Tail
print("\nLast 5 rows:")
print(transactions.tail())




Transactions DataFrame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

First 5 rows:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Last 5 rows:
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   

In [18]:
# Shape
print("\nShape:")
print(transactions.shape)

# Column names
print("\nColumn Names:")
print(transactions.columns)

# Data types
print("\nData Types:")
print(transactions.dtypes)

# Basic information
print("\nBasic Information:")
transactions.info()



Shape:
(10, 4)

Column Names:
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

Data Types:
TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

Basic Information:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     str  
 2   Region           10 non-null     str  
 3   Amount           10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 452.0 bytes


In [15]:
# ProductCategory and Amount
print("\nProduct Category and Amount:")
print(transactions[['ProductCategory', 'Amount']])

# Last 3 columns
print("\nLast 3 Columns:")
print(transactions.iloc[:, -3:])




Product Category and Amount:
  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

Last 3 Columns:
  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [16]:
# Region = North AND Amount > 200
print("\nNorth Region with Amount greater than 200:")
print(
    transactions[
        (transactions['Region'] == 'North') &
        (transactions['Amount'] > 200)
    ]
)

# ProductCategory value counts
print("\nProduct Category Counts:")
print(transactions['ProductCategory'].value_counts())

# Unique Regions
print("\nUnique Regions:")
print(transactions['Region'].unique())

# Mean Amount by Region
print("\nMean Amount by Region:")
print(transactions.groupby('Region')['Amount'].mean())


North Region with Amount greater than 200:
   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

Product Category Counts:
ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

Unique Regions:
<StringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

Mean Amount by Region:
Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [19]:
# 3. Manipulating the DataFrame

# Modify Amount for TransactionID 102
transactions.loc[
    transactions['TransactionID'] == 102,
    'Amount'
] = 165

print("\nAfter modifying TransactionID 102:")
print(transactions)




After modifying TransactionID 102:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [20]:
# Add Discount column
transactions['Discount'] = transactions['Amount'] * 0.10

print("\nAfter adding Discount:")
print(transactions)


After adding Discount:
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [21]:
# Remove TransactionID 109
transactions = transactions[
    transactions['TransactionID'] != 109
]

print("\nAfter removing TransactionID 109:")
print(transactions)



After removing TransactionID 109:
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [22]:
# Delete Discount column
transactions = transactions.drop('Discount', axis=1)

print("\nFinal DataFrame:")
print(transactions)


Final DataFrame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
